# Generated by Django 5.0.1 on 2024-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(default='<function uuid4 at 0x00000219F7733CE0>', max_length=64, primary_key=True, serialize=False)),
                ('code', models.TextField(max_length=1024)),
                ('dir', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='<function uuid4 at 0x00000219F7733CE0>', max_length=64, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
