# Generated by Django 5.0.1 on 2024-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='code', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.CharField(default='hjbdsfy3490re-f-ev9huh784', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x0000019826F33CE0>', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x0000019826F33CE0>', max_length=64, primary_key=True, serialize=False),
        ),
    ]
